
spring:
  application:
    name: upwork-demo
  datasource:
    url: jdbc:postgresql://localhost:5435/upwork_demo_db
    username: upworkuser
    password: upworkpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect